server/baketapp/urls.py
from django.urls import path

import baketapp.views as baketapp

app_name = 'baketapp'

urlpatterns = [
    path('', baketapp.baket, name='view'),
    path('add/<int:pk>/', baketapp.baket_add, name='add'),
    path('remove/<int:pk>/', baketapp.baket_remove, name='remove'),
]

server/products/routes/urls.py
from django.urls import path

from products.views import RestProductListView

app_name = 'rest_products'



urlpatterns = [
    path('', RestProductListView.as_view(), name='list')
]

server/products/urls.py
from django.urls import path

from .views import catalog, product_detail_view, product_category_show, ProductListView

#app_name='products'



urlpatterns = [
    path('', ProductListView.as_view()),
    path('<int:idx>/', product_detail_view),
    path('categories/<int:idcat>/', product_category_show),
]

server/server/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from products.viewset import ProductViewSet, CategoryViewSet


router = DefaultRouter()

router.register('products', ProductViewSet)
router.register('category', CategoryViewSet)

django_router = [
    path('catalog/', include('products.routes.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('django-api/', include(django_router)),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('catalog/', include('products.urls')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('baket/', include('baketapp.urls', namespace='baket')),
    path('administration/', include('adminapp.urls', namespace='adminapp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/products/models.py
from django.db import models

# Create your models here.



class Category(models.Model):
    name = models.CharField(
        max_length=30
    )

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(
        max_length=15
    )
    article = models.CharField(
        max_length=6
    )
    country = models.CharField(
        max_length=15
    )
    pakaging = models.CharField(
        max_length=30
    )
    figure = models.CharField(
        max_length=15
    )

    image = models.ImageField(
        upload_to='',
        blank=True
    )
    category_id = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.name}"



class Description(models.Model):
    article = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )

    material = models.CharField(
        max_length=15
    )

    size = models.FloatField()

    dimension = models.CharField(
        max_length=2
    )

    def __str__(self):
        return f"{self.article.name}"

class Package(models.Model):
    width = models.FloatField()
    heigth = models.FloatField()
    length = models.FloatField()
    volume = models.FloatField()
    article = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.article.name}"

server/products/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product, Description, Package, Category
from django.views.generic import ListView
from baketapp.models import Baket
from django.http import JsonResponse
from django.urls import reverse, reverse_lazy
# Create your views here.

class RestProductListView(ListView):
    model = Product
    template_name = 'products/catalog.html'
    paginate_by = 2
    login_url = reverse_lazy('accounts:login')

    def serialize_object_list(self, queryset):
        return list(
            map(
                lambda itm: {
                    'id': itm.id,
                    'name': itm.name,
                    'image': itm.image.url if itm.image else None
                }, queryset
            )
        )

    def get_context_data(self, **kwargs):
        context = super(RestProductListView, self).get_context_data(**kwargs)

        data = {}

        page = context.get('page_obj')
        route_url = reverse('rest_products:list')

        data['next_url'] = None
        data['previous_url'] = None
        data['page'] = page.number
        data['count'] = page.paginator.count
        data['results'] = self.serialize_object_list(page.object_list)

        if page.has_previous():
            data['previous_url'] = f'{route_url}?page={page.previous_page_number()}'

        if page.has_next():
            data['next_url'] = f'{route_url}?page={page.next_page_number()}'


        return data


    def render_to_response(self, context, **response_kwargs):
        return JsonResponse(context)

class ProductListView(ListView):
    model = Product
    template_name = 'products/catalog.html'
    paginate_by = 2
    login_url = reverse_lazy('accounts:login')


def catalog(request):
    baket = []
    if request.user.is_authenticated:
        baket = Baket.objects.filter(user=request.user)


    data = Product.objects.all()

    return render(request,
                    'products/catalog.html',
                     {'object_list': data,
                      'baket': baket
                      }
                  )

def product_detail_view(request, idx):


    category_name = Category.objects.get(product=idx)

    data = Product.objects.get(pk=idx)
    data_description = Description.objects.get(pk=idx)
    data_package = Package.objects.get(pk=idx)

    return render(
        request,
        'products/prod.html',
        {'object_data': data,
         'object_description': data_description,
         'object_package': data_package,
         'object_category': category_name


        }
    )
#'object_category': category_name

def product_category_show(request, idcat):

    data = Product.objects.filter(category_id=idcat)
    data_category_name = get_object_or_404(Category, pk=idcat)

    print(data)
    print(data_category_name)

    return render(
        request,
        'products/category_list.html',
        {'object_data': data,
         'object_category': data_category_name
         }
    )

server/products/templates/products/catalog.html
{% extends 'server/master.html' %}
{% block paragraf %}
<h1>Каталог</h1>
{% endblock %}
{% block page_content %}
		<div class="paragraf">
			<h3>Игрушки</h3>
			{% for object in object_list %}
			<div class="toy">
				<div class="photo2">
					<p><a href="/catalog/{{ object.id }}/"><img src="/media/{{ object.image }}" alt="sorry" width="150" heigth="150" hspace="4" vspace="4"></a></p>
				</div>
				<div class="linkproduct2">
					<a href="/catalog/{{ object.id }}/">{{ object.name|title }}</a>
					<a href=""></a>
					<br><br>
				</div>
			</div>
			{% endfor %}

		</div>
		{% if page_obj.has_next %}
			<button class="show-more-button">Show more</button>
		{% endif %}

		<hr>

{% endblock %}

{% block page_js %}
<script src="/static/products/js/products.js"></script>
<script>
	const products = document.querySelector('.paragraf');
	const showMoreButton = document.querySelector('.show-more-button');

	let productsUrl = '{% url 'rest_products:list' %}?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}'

	const showMore = () => {
		fetch(productsUrl)
			.then(response => response.json())
			.then(
				data => {
					data.results.map(
						itm => products.innerHTML += renderProduct(itm)
					)
					if (data.next_url) {
						productUrl = data.next_url
					} else {
						showMoreButton.classList.add('show-more-button_hidden')
					}

				}
			)

	}

	showMoreButton.addEventListener('click',showMore)
</script>
{% endblock %}

server/products/templates/products/category_list.html
{% extends 'server/master.html' %}
{% block paragraf %}
<h1>Каталог</h1>
{% endblock %}
{% block page_content %}
		<div class="paragraf">
			<h3>Товары категории {{ object_category.name }}</h3>
            {% for object in object_data %}
			<div class="toy">
				<div class="photo2">
					<p><a href="/catalog/{{ object.id }}/"><img src="/media/{{ object.image }}" alt="sorry" width="150" heigth="150" hspace="4" vspace="4"></p></a>
				</div>
				<div class="linkproduct2">
					<a href="/catalog/{{ object.id }}/">{{ object.name|title }}</a>
					<a href=""></a>
					<br><br>
				</div>
			</div>
			{% endfor %}


		</div>
		<hr>
{% endblock %}

server/products/templates/products/prod.html
{% extends 'server/master.html' %}
{% block paragraf %}
<h1>Игрушка</h1>
{% endblock %}
{% block page_content %}

<h1>{{ object_data.name|title }}</h1>
<div class="fotoproduct">
	<a id="decor" href="/media/{{  object_data.image }}" target="_blank"><img id="decor" src="/media/{{  object_data.image }}" alt="sorry" width="200" heigth="200" hspace="4" vspace="4"></a>
</div>
<div class="fotoproduct fdesc">
	<p id="description">{{ object_data.name }}</p>
	<a href="/catalog/categories/{{ object_category.id }}"><p id="description_category">Категория: {{ object_category.name }}</p></a>
</div>
<div class="fotoproduct bdesc">
	<form action="{% url 'baket:add' object_data.pk %}">
		<input type="submit" style="width: 150px; height: 50px; font-size: 18px;" value="В карзину" class="bbuy">
	</form>
</div>

<div class="productdesc">
	<h3>Техничексие характеристики</h3>
		<table class="desctable">
			<tr>
				<td>Материал</td>
				<td>Высота</td>
				<td>Размер</td>
			</tr>
			<tr>
				<td>{{ object_description.material }}</td>
				<td>{{ object_description.size }}</td>
				<td>{{ object_description.dimension }}</td>
			</tr>
		</table>
		<h3>Характеристики</h3>
		<ul id="all_property">
			<li>Артикул: {{ object_data.article }}</li>
			<li>Страна производитель: {{ object_data.country }}</li>
			<li>Упаковка: {{ object_data.pakaging }}</li>
			<li>Тип: {{ object_data.figure }}</li>
		</ul>
		<h3>Упаковка:</h3>
		<ul id="package">
			<li>Длина упаковки: {{ object_package.length }} м</li>
			<li>Ширина упаковки: {{ object_package.width }} м</li>
			<li>Высота упаковки: {{ object_package.heigth }} м</li>
			<li>Объем упаковки: {{ object_package.volume }} м3</li>
		</ul>
</div>
<hr>
{% endblock %}