server/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path
from adminapp.views import UserCreateView, UserAddView
app_name = 'admin_app'


urlpatterns = [
    path('', adminapp.show_options, name='show_options'),

    path('user/create/', adminapp.user_create, name='user_create'),
    path('user/read/', adminapp.user_read, name='user_read'),
    path('user/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('user/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('user/show/', UserAddView.as_view(), name='show'),


    path('category/read/', adminapp.category_read, name='category_read'),
    path('category/create/', adminapp.category_create, name='category_create'),
    path('category/update/<int:pk>', adminapp.category_update, name='category_update'),
    path('category/delete/<int:pk>', adminapp.category_delete, name='category_delete'),

    path('product/read/', adminapp.product_read, name='product_read'),
    path('product/create/', adminapp.product_create, name='product_create'),
    path('product/update/<int:pk>', adminapp.product_update, name='product_update'),
    path('product/delete/<int:pk>', adminapp.product_delete, name='product_delete'),
]

server/products/routes/urls.py
from django.urls import path

from products.views import RestProductListView

app_name = 'rest_products'



urlpatterns = [
    path('', RestProductListView.as_view(), name='list')
]

server/products/urls.py
from django.urls import path

from .views import catalog, product_detail_view, product_category_show, ProductListView

#app_name='products'



urlpatterns = [
    path('', ProductListView.as_view()),
    path('<int:idx>/', product_detail_view),
    path('categories/<int:idcat>/', product_category_show),
]

server/server/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from products.viewset import ProductViewSet, CategoryViewSet


router = DefaultRouter()

router.register('products', ProductViewSet)
router.register('category', CategoryViewSet)

django_router = [
    path('catalog/', include('products.routes.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('django-api/', include(django_router)),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('catalog/', include('products.urls')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('baket/', include('baketapp.urls', namespace='baket')),
    path('administration/', include('adminapp.urls', namespace='adminapp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/adminapp/models.py
from django.db import models

# Create your models here.

server/products/models.py
from django.db import models

# Create your models here.



class Category(models.Model):
    name = models.CharField(
        max_length=30
    )

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(
        max_length=15
    )
    article = models.CharField(
        max_length=6
    )
    country = models.CharField(
        max_length=15
    )
    pakaging = models.CharField(
        max_length=30
    )
    figure = models.CharField(
        max_length=15
    )

    image = models.ImageField(
        upload_to='',
        blank=True
    )
    category_id = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.name}"



class Description(models.Model):
    article = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )

    material = models.CharField(
        max_length=15
    )

    size = models.FloatField()

    dimension = models.CharField(
        max_length=2
    )

    def __str__(self):
        return f"{self.article.name}"

class Package(models.Model):
    width = models.FloatField()
    heigth = models.FloatField()
    length = models.FloatField()
    volume = models.FloatField()
    article = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.article.name}"

server/adminapp/forms.py
from django import forms
from products.models import Product, Category
from accounts.models import AccountUser

class UserCreateView(forms.ModelForm):
    class Meta:
        model = AccountUser
        fields = ['username', 'age', 'avatar']


class ProductCreateView(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'article', 'country', 'pakaging','figure', 'image','category_id']


class CategoryCreateView(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

server/adminapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from accounts.models import AccountUser
from products.models import Product, Category
from django.contrib.auth.decorators import user_passes_test
from adminapp.forms import UserCreateView, ProductCreateView, CategoryCreateView
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy

# Create your views here.
@user_passes_test(lambda u: u.is_superuser)
def show_options(request):
    title = 'Админка/выбор опции'

    content = {
        'title': title,
    }

    return render(request, 'adminapp/base.html', content)

class UserCreateView(ListView):
    model = AccountUser
    template_name = 'adminapp/users_test.html'

class UserAddView(CreateView):
    model = AccountUser
    template_name = 'adminapp/users_cr.html'

def user_create(request):
    form = UserCreateView()
    success_url = reverse_lazy('adminapp:user_read')
    if request.method == 'POST':
        form = UserCreateView(data=request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/create_user.html', {'form': form})


def user_read(request):
    title = 'админка/пользователи '

    objects = AccountUser.objects.all()

    content = {
        'title': title,
        'objects': objects
    }

    return render(request, 'adminapp/users.html', content)

def user_update(request, pk):
    obj = get_object_or_404(AccountUser, pk=pk)
    form = UserCreateView(instance=obj)
    success_url = reverse_lazy('adminapp:user_read')

    if request.method == 'POST':
        form = UserCreateView(
            request.POST,
            files=request.FILES,
            instance=obj
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/update_user.html', {'form': form})


def user_delete(request, pk):
    obj = get_object_or_404(AccountUser, pk=pk)
    success_url = reverse_lazy('adminapp:user_read')
    if request.method == 'POST':
        obj.delete()
        return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/delete_user.html', {'obj': obj})


def category_read(request):
    title = 'админка/категории'

    objects = Category.objects.all()

    content = {
        'title': title,
        'objects': objects
    }

    return render(request, 'adminapp/category.html', content)

def category_create(request):
    form = CategoryCreateView()
    success_url = reverse_lazy('adminapp:category_read')
    if request.method == 'POST':
        form = CategoryCreateView(data=request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/create_category.html', {'form': form})

def category_update(request, pk):
    obj = get_object_or_404(Category, pk=pk)
    form = CategoryCreateView(instance=obj)
    success_url = reverse_lazy('adminapp:category_read')

    if request.method == 'POST':
        form = CategoryCreateView(
            request.POST,
            files=request.FILES,
            instance=obj
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/update_category.html', {'form': form})

def category_delete(request, pk):
    obj = get_object_or_404(Category, pk=pk)
    success_url = reverse_lazy('adminapp:category_read')
    if request.method == 'POST':
        obj.delete()
        return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/delete_category.html', {'obj': obj})

def product_read(request):
    title = 'админка/продукты'

    objects = Product.objects.all()

    content = {
        'title': title,
        'objects': objects
    }

    return render(request, 'adminapp/product.html', content)

def product_create(request):
    form = ProductCreateView()
    success_url = reverse_lazy('adminapp:product_read')
    if request.method == 'POST':
        form = ProductCreateView(data=request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/create_product.html', {'form': form})


def product_update(request, pk):
    obj = get_object_or_404(Product, pk=pk)
    form = ProductCreateView(instance=obj)
    success_url = reverse_lazy('adminapp:product_read')

    if request.method == 'POST':
        form = ProductCreateView(
            request.POST,
            files=request.FILES,
            instance=obj
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/update_product.html', {'form': form})

def product_delete(request, pk):
    obj = get_object_or_404(Product, pk=pk)
    success_url = reverse_lazy('adminapp:product_read')
    if request.method == 'POST':
        obj.delete()
        return HttpResponseRedirect(success_url)

    return render(request, 'adminapp/delete_product.html', {'obj': obj})

server/products/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product, Description, Package, Category
from django.views.generic import ListView
from baketapp.models import Baket
from django.http import JsonResponse
from django.urls import reverse, reverse_lazy
# Create your views here.

class RestProductListView(ListView):
    model = Product
    template_name = 'products/catalog.html'
    paginate_by = 2
    login_url = reverse_lazy('accounts:login')

    def serialize_object_list(self, queryset):
        return list(
            map(
                lambda itm: {
                    'id': itm.id,
                    'name': itm.name,
                    'image': itm.image.url if itm.image else None
                }, queryset
            )
        )

    def get_context_data(self, **kwargs):
        context = super(RestProductListView, self).get_context_data(**kwargs)

        data = {}

        page = context.get('page_obj')
        route_url = reverse('rest_products:list')

        data['next_url'] = None
        data['previous_url'] = None
        data['page'] = page.number
        data['count'] = page.paginator.count
        data['results'] = self.serialize_object_list(page.object_list)

        if page.has_previous():
            data['previous_url'] = f'{route_url}?page={page.previous_page_number()}'

        if page.has_next():
            data['next_url'] = f'{route_url}?page={page.next_page_number()}'


        return data


    def render_to_response(self, context, **response_kwargs):
        return JsonResponse(context)

class ProductListView(ListView):
    model = Product
    template_name = 'products/catalog.html'
    paginate_by = 2
    login_url = reverse_lazy('accounts:login')


def catalog(request):
    baket = []
    if request.user.is_authenticated:
        baket = Baket.objects.filter(user=request.user)


    data = Product.objects.all()

    return render(request,
                    'products/catalog.html',
                     {'object_list': data,
                      'baket': baket
                      }
                  )

def product_detail_view(request, idx):


    category_name = Category.objects.get(product=idx)

    data = Product.objects.get(pk=idx)
    data_description = Description.objects.get(pk=idx)
    data_package = Package.objects.get(pk=idx)

    return render(
        request,
        'products/prod.html',
        {'object_data': data,
         'object_description': data_description,
         'object_package': data_package,
         'object_category': category_name


        }
    )
#'object_category': category_name

def product_category_show(request, idcat):

    data = Product.objects.filter(category_id=idcat)
    data_category_name = get_object_or_404(Category, pk=idcat)

    print(data)
    print(data_category_name)

    return render(
        request,
        'products/category_list.html',
        {'object_data': data,
         'object_category': data_category_name
         }
    )

server/adminapp/templates/adminapp/category.html
{% extends 'adminapp/base.html' %}

{% block page_content %}
<div class="category_list">
    <button>
        <a href="{% url 'admin_app:category_create' %}">
            Новыя категория
        </a>
    </button>
    {% for object in objects %}

             <div class="product">
                {{ object.name|title }}
                <button>
                    <a href="{% url 'admin_app:category_update' object.pk %}">
                        редактировать категорию
                    </a>
                </button>
                <button>
                    <a href="{% url 'admin_app:category_delete' object.pk %}">
                        удалить категорию
                    </a>
                </button>
            </div>

    {% endfor %}
</div>
{% endblock %}

server/adminapp/templates/adminapp/create_category.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="field-group">
        <label for="{{ field.name }}">{{ field.name }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/create_user.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="field-group">
        <label for="{{ field.name }}">{{ field.name }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/delete_category.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    <span>Товар будет удален {{ obj.name }}</span>
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/delete_product.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    <span>Товар будет удален {{ obj.name }}</span>
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/delete_user.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    <span>Пользователь будет удален {{ obj.username }}</span>
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/options.html
{% extends 'server/master.html' %}

{% block page_content %}
<h1>{{ title }}</h1>
<ul>
    {% for option in options_list %}
    <li><a href="/administration/{{ option }}/">{{ option }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

server/adminapp/templates/adminapp/product.html
{% extends 'adminapp/base.html' %}

{% block page_content %}
<div class="product_list">
    <button>
        <a href="{% url 'admin_app:product_create' %}">
            Новый товар
        </a>
    </button>
    {% for object in objects %}

             <div class="product">
                {{ object.name|title }}
                <button>
                    <a href="{% url 'admin_app:product_update' object.pk %}">
                        редактировать товар
                    </a>
                </button>
                <button>
                    <a href="{% url 'admin_app:product_delete' object.pk %}">
                        удалить товар
                    </a>
                </button>
            </div>

    {% endfor %}
</div>
{% endblock %}

server/adminapp/templates/adminapp/update_category.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="field-group">
        <label for="{{ field.name }}">{{ field.name }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/update_product.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="field-group">
        <label for="{{ field.name }}">{{ field.name }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/update_user.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="field-group">
        <label for="{{ field.name }}">{{ field.name }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/user_cr.html
{% extends 'adminapp/base.html' %}


{% block page_content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in object_list %}
    <div class="field-group">
        <label for="{{ field.name }}">{{ field.name }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <input type="submit">
</form>
{% endblock %}

server/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}

{% block page_content %}
<div class="users_list">
    <button>
        <a href="{% url 'admin_app:user_create' %}">
            Новый пользователь
        </a>
    </button>
    {% for object in objects %}
        <div
            class="user_record {%if not object.is_active %} not_active{%endif %}">
            <img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}" alt="{{ object.username }}">
            <div class="user_role">
                {% if object.is_superuser %}
                администратор
                {% else %}
                пользователь
                {% endif %}
                <button>
                    <a href="{% url 'admin_app:user_update' object.pk %}">
                        редактировать
                    </a>
                </button>
                <button>
                    <a href="{% url 'admin_app:user_delete' object.pk %}">
                        удалить
                    </a>
                </button>
            </div>

        </div>
    {% endfor %}
</div>
{% endblock %}

server/adminapp/templates/adminapp/users_test.html
{% extends 'adminapp/base.html' %}

{% block page_content %}
<div class="users_list">
    <button>
        <a href="{% url 'admin_app:user_create' %}">
            Новый пользователь
        </a>
    </button>
    {% for object in object_list %}
        <div class="user_record {%if not object.is_active %} not_active{%endif %}">
            <img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}" alt="{{ object.username }}">
            <div class="user_role">
                {% if object.is_superuser %}
                администратор
                {% else %}
                пользователь
                {% endif %}
                <button>
                    <a href="{% url 'admin_app:user_update' object.pk %}">
                        редактировать
                    </a>
                </button>
                <button>
                    <a href="{% url 'admin_app:user_delete' object.pk %}">
                        удалить
                    </a>
                </button>
            </div>

        </div>
    {% endfor %}
</div>
{% endblock %}