server/accounts/urls.py
from django.urls import path

import accounts.views as accounts

app_name = 'accounts'

urlpatterns = [
    path('login/', accounts.login, name='login'),
    path('logout/', accounts.logout, name='logout'),
    path('register/', accounts.register, name='register'),
    path('edit/', accounts.edit, name='edit'),
]

server/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path
from adminapp.views import UserCreateView, UserAddView
app_name = 'admin_app'


urlpatterns = [
    path('', adminapp.show_options, name='show_options'),

    path('user/create/', adminapp.user_create, name='user_create'),
    path('user/read/', adminapp.user_read, name='user_read'),
    path('user/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('user/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('user/show/', UserAddView.as_view(), name='show'),


    path('category/read/', adminapp.category_read, name='category_read'),
    path('category/create/', adminapp.category_create, name='category_create'),
    path('category/update/<int:pk>', adminapp.category_update, name='category_update'),
    path('category/delete/<int:pk>', adminapp.category_delete, name='category_delete'),

    path('product/read/', adminapp.product_read, name='product_read'),
    path('product/create/', adminapp.product_create, name='product_create'),
    path('product/update/<int:pk>', adminapp.product_update, name='product_update'),
    path('product/delete/<int:pk>', adminapp.product_delete, name='product_delete'),
]

server/server/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from products.viewset import ProductViewSet, CategoryViewSet


router = DefaultRouter()

router.register('products', ProductViewSet)
router.register('category', CategoryViewSet)

django_router = [
    path('catalog/', include('products.routes.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('django-api/', include(django_router)),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('catalog/', include('products.urls')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('baket/', include('baketapp.urls', namespace='baket')),
    path('administration/', include('adminapp.urls', namespace='adminapp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/server/templates/includes/menu.html
<div class="divmenu">
    <ul class="menu">
		<li><a href="/">Главная</a></li>
		<li><a href="/catalog/">Каталог</a></li>
		<li><a href="/contacts/">Контакты</a></li>
		{% if user.is_authenticated %}
		<li>
			<a href="{% url 'accounts:edit' %}">
				{{ user.username|default:'User' }}
			</a>
		</li>
		{% endif %}
		<li>
			{% if user.is_authenticated %}
				<a href="{% url 'accounts:logout' %}">Выйти</a>
			{% else %}
				<a href="{% url 'accounts:login' %}">Войти</a>
				<li>
					<a href="{% url 'accounts:register' %}">Регистрация</a>
				</li>
			{% endif %}
		</li>
		<li>
			<a href="/baket/">Корзина
				<span>{% if baket %} {{ baket|length }} {% endif %}</span>
			</a>
		</li>
		{% if user.is_superuser %}
		<li>

			<a href="{% url 'admin_app:show_options' %}">Админка</a>

		</li>
		{% endif %}
	</ul>
</div>